common/urls.py
from django.urls import path
from . import views

app_name = 'common_app'
urlpatterns = [
   path('',views.common_index,name='index'),
   path('cart',views.cart,name='cart'),
   path('checkout',views.checkout,name='checkout'),
   path('customer_reg',views.customer_reg,name='customer_reg'),
   path('customer_login',views.customer_login,name='customer_login'),
   path('seller_login',views.seller_login,name='seller_login'),
   path('seller_reg',views.seller_reg,name='seller_reg'),
   

]

customer/urls.py
from django.urls import path,include
from . import views

app_name = 'customer_app'


urlpatterns = [
    path('customer_home',views.customer_home,name='customer_home'),
    path('cus_profile',views.cus_profile,name='cus_profile'),

]

e_commerce/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('common.urls')),
    path('customer/',include('customer.urls')),
    path('seller/',include('seller.urls'))
]+static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

seller/urls.py
from django.urls import path,include
from .import views

app_name = 'seller_app'
urlpatterns = [
    path('seller_home',views.seller_home,name='seller_home'),

]

common/models.py
from django.db import models

# Create your models here.

class Customer(models.Model):
    name = models.CharField(max_length=20)
    email = models.CharField(max_length=20)
    password = models.CharField(max_length=20)

    class Meta:
        db_table ='customer_tb'

class Seller(models.Model):
    name = models.CharField(max_length=20)
    email = models.CharField(max_length=20)
    password = models.CharField(max_length=20)
    user_name=models.IntegerField(default=0)
    account=models.BigIntegerField()
    phone=models.BigIntegerField()
    ifsc=models.BigIntegerField()
    address=models.CharField(max_length=30)
    seller_pic= models.ImageField(upload_to='seller/')



    class Meta:
        db_table ='seller_tb'

customer/models.py
from django.db import models

# Create your models here.

seller/models.py
from django.db import models

# Create your models here.

common/views.py
from django.shortcuts import render
from . models import Customer
from . models import Seller
from random import randint
from django.conf import settings
from django.core.mail import send_mail

# Create your views here.


def common_index(request):
    return render(request, 'common_templates/index.html')


def cart(request):
    return render(request, 'common_templates/cart.html')


def checkout(request):
    return render(request, 'common_templates/checkout.html')


def customer_reg(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']

        new_customer = Customer(name=username, email=email, password=password)
        new_customer.save()  # inserting in to table as row

    return render(request, 'common_templates/customer_reg.html')


def customer_login(request):
    return render(request, 'common_templates/customer_login.html')


def seller_login(request):
    return render(request, 'common_templates/seller_login.html')


def seller_reg(request):
    msg = ''
    if request.method == 'POST':

            seller_name = request.POST['seller_name']
            email = request.POST['email']
            phone = request.POST['phone']
            account = request.POST['account']
            ifsc = request.POST['ifsc']
            seller_pic = request.FILES['seller_pic']
            address = request.POST['address']
            user_name= randint(1111, 9999)
            pwd = 'sell-'+str(user_name)+'-'+phone[6:10]

            newseller = Seller(name=seller_name, email=email, phone=phone, account=account,ifsc=ifsc,
             seller_pic=seller_pic, address=address, user_name=user_name,password=pwd)
            newseller.save()
            msg = 'created successfully'
            email_subject='account user name and password'
            email_content='user name :'+str(user_name) + 'password' + pwd

            send_mail(
                email_subject,
                email_content,
                settings.EMAIL_HOST_USER,
                [email,]
            )
    return render(request, 'common_templates/seller_reg.html',{'message':msg})

    

customer/views.py
from django.shortcuts import render

# Create your views here.

def customer_home(request):
    return render(request,'customer_templates/customer_home.html')

def cus_profile(request):
    return render(request,'customer_templates/cus_profile.html')

seller/views.py
from django.shortcuts import render

# Create your views here.

def seller_home(request):
    return render(request,'seller_templates/seller_home.html')

common/templates/common_templates/cart.html
{% extends './main.html' %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="box-element">

            <a  class="btn btn-outline-dark" href="{% url 'common_app:index' %}">&#x2190; Continue Shopping</a>

            <br>
            <br>
            <table class="table">
                <tr>
                    <th><h5>Items: <strong>3</strong></h5></th>
                    <th><h5>Total:<strong> $42</strong></h5></th>
                    <th>
                        <a  style="float:right; margin:5px;" class="btn btn-success" href="{% url 'common_app:checkout' %}">Checkout</a>
                    </th>
                </tr>
            </table>

        </div>

        <br>
        <div class="box-element">
            <div class="cart-row">
                <div style="flex:2"></div>
                <div style="flex:2"><strong>Item</strong></div>
                <div style="flex:1"><strong>Price</strong></div>
                <div style="flex:1"><strong>Quantity</strong></div>
                <div style="flex:1"><strong>Total</strong></div>
            </div>
            
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{% static 'images/placeholder.png' %}"></div>
                <div style="flex:2"><p>Product 1</p></div>
                <div style="flex:1"><p>$20</p></div>
                <div style="flex:1">
                    <p class="quantity">2</p>
                    <div class="quantity">
                        <img class="chg-quantity" src="{% static  'images/arrow-up.png' %}">
                
                        <img class="chg-quantity" src="{% static  'images/arrow-down.png' %}">
                    </div>
                </div>
                <div style="flex:1"><p>$32</p></div>
            </div>

        </div>
    </div>
</div>
{% endblock content %}

common/templates/common_templates/checkout.html
{% extends './main.html' %}

{% load static %}
 {% block content %}
     <div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form">
					<div id="user-info">
						<div class="form-field">
							<input required class="form-control" type="text" name="name" placeholder="Name..">
						</div>
						<div class="form-field">
							<input required class="form-control" type="email" name="email" placeholder="Email..">
						</div>
					</div>
					
					<div id="shipping-info">
						<hr>
						<p>Shipping Information:</p>
						<hr>
						<div class="form-field">
							<input class="form-control" type="text" name="address" placeholder="Address..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="city" placeholder="City..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="state" placeholder="State..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
						</div>
						<div class="form-field">
							<input class="form-control" type="text" name="country" placeholder="Zip code..">
						</div>
					</div>

					<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
				</form>
			</div>

			<br>
			<div class="box-element hidden" id="payment-info">
				<small>Paypal Options</small>
			</div>
			
		</div>

		<div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'common_app:cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{% static 'images/placeholder.png' %}"></div>
					<div style="flex:2"><p>Product 1</p></div>
					<div style="flex:1"><p>$20.00</p></div>
					<div style="flex:1"><p>x2</p></div>
				</div>
				<h5>Items:   2</h5>
				<h5>Total:   $4</h5>
			</div>
		</div>
	</div>

{% endblock content %}

common/templates/common_templates/customer_login.html
{% extends './main.html' %}
{% load static %}
{% block link %}	
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
{% endblock %}
{% block content %}

<style>
  
    .user_card {
        width: 370px;
        height: 350px;
        margin-top: 100px;
        margin-bottom: 50px;
        background: #74cfbf;
        position: relative;
        display: flex;
        justify-content: center;
        flex-direction: column;
        padding: 10px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        border-radius: 5px;

    }

    .form_container {
        margin-top: 20px;
    }

    #form-title{
        color: #fff;
    }
    .login_btn {
        width: 100%;
        background: #33ccff !important;
        color: white !important;
    }
    .login_btn:focus {
        box-shadow: none !important;
        outline: 0px !important;
    }
    .login_container {
        padding: 0 2rem;
    }
    .input-group-text {
        background: #f7ba5b !important;
        color: white !important;
        border: 0 !important;
        border-radius: 0.25rem 0 0 0.25rem !important;
    }
    .input_user,
    .input_pass:focus {
        box-shadow: none !important;
        outline: 0px !important;
    }

</style>

</head>
<body>
<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">CUSTOMER LOGIN</h3>
            </div>
            <div class="d-flex justify-content-center form_container">

                <form method="POST" action="">
                    
                    <div class="input-group mb-4">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                        </div>
                        <input class=" border border-none" type="email" name="email" placeholder="email">
                    </div>
                    <div class="input-group mb-4">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input class=" border border-none" type="text" name="password" placeholder="password">
                    </div>
                    

                       <div class="d-flex justify-content-center mt-3 login_container">
                        <a href="{% url  'customer_app:customer_home'  %}"> <button class="btn login_btn" type="button">Login</button></a>
                       </div>
                </form>
            </div>
    
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    dont have an account? <a href="{% url 'common_app:customer_reg' %}" class="ml-2">Register</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

common/templates/common_templates/customer_reg.html
{% extends './main.html' %}
{% load static %}
{% block link %}	
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
{% endblock %}
{% block content %}

<style>
  
    .user_card {
        width: 350px;
        margin-top: 100px;
        margin-bottom: 50px;
        background: #74cfbf;
        position: relative;
        display: flex;
        justify-content: center;
        flex-direction: column;
        padding: 10px;
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        -moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
        border-radius: 5px;

    }

    .form_container {
        margin-top: 20px;
    }

    #form-title{
        color: #fff;
    }
    .login_btn {
        width: 100%;
        background: #33ccff !important;
        color: white !important;
    }
    .login_btn:focus {
        box-shadow: none !important;
        outline: 0px !important;
    }
    .login_container {
        padding: 0 2rem;
    }
    .input-group-text {
        background: #f7ba5b !important;
        color: white !important;
        border: 0 !important;
        border-radius: 0.25rem 0 0 0.25rem !important;
    }
    .input_user,
    .input_pass:focus {
        box-shadow: none !important;
        outline: 0px !important;
    }

</style>

</head>
<body>
<div class="container h-100">
    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">
                <h3 id="form-title">CUSTOMER REGISTER</h3>
            </div>
            <div class="d-flex justify-content-center form_container">

                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input  class=" border border-none" type="text" name="username" placeholder="name">
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
                        </div>
                        <input class=" border border-none" type="email" name="email" placeholder="email">
                    </div>
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input class=" border border-none" type="text" name="password" placeholder="password">
                    </div>
                    <!-- <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input class="border border-none" type="text" name="password2" placeholder="conformpassword">
                    </div> -->

                       <div class="d-flex justify-content-center mt-3 login_container">
                         <input class="btn login_btn" type="submit" value="Register Account">
                       </div>
                </form>
            </div>
    
            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Already have an account? <a href="{% url 'common_app:customer_login' %}" class="ml-2">Login</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

common/templates/common_templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  {% block link %} {% endblock %}



  <title>Document</title>

</head>

<body>
  
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'common_app:index' %}">Eco</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'common_app:index' %}">Home</a>
          </li>
        </ul>
        <div class="form-inline my-2 my-lg-0">
          <button class="btn btn-warning" onclick="disp()">Login</button>

          <a href="{% url 'common_app:cart' %}">
            <img id="cart-icon" src="{% static 'images/cart.png' %}">
          </a>
          <p id="cart-total">0</p>

        </div>

      </div>
    </div>
  </nav>
  <div class="row" id="login_detail">
    <div class="col-9"></div>
    <div class="col">


      <div class="alert alert-success" role="alert">
        <div class="row text-center">
          <div class="col">
            <a href="{% url 'common_app:customer_login' %}" class="alert-link">customer login</a>
          </div>
          <div class="col">
            <a href="{% url 'common_app:seller_login' %}" class="alert-link">seller login</a>
          </div>
        </div>
      </div>
    </div>
  </div>



  <div class="container">
    <br>
    {% block content %}
   


    {% endblock content %}
  </div>
  <br><br><br>
  <div class="footer">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <div class="container-fluid ">
      <div id="social" class="col-md-6 col-md-offset-3 text-center">

        <a href="#" class="fa fa-facebook"></a>
        <a href="#" class="fa fa-twitter"></a>
        <a href="#" class="fa fa-instagram"></a>


      </div>

    </div>
  </div>
  </div>






  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"></script>

  <script>

    function disp() {

      var a = document.getElementById('login_detail')
      
      if (a.style.display == 'none') {
        a.style.display = 'flex';
      }
      else {
        a.style.display = 'none';

      }
    }
  </script>
</body>

</html>

customer/templates/customer_templates/customer_home.html
{% extends './customer_main.html' %}
{% load static %}
{% block content %}

<div class="row">
    <div class="col-4">
<div class="card" style="width: 18rem;background:#8ababf;">
    <div class="card-body text-center">
      <h5 class="card-title">Total Order</h5>
      <hr>
      <h2 class="card-text">6</h2>
      
    </div>
  </div>
</div>
<div class="col-4">
  <div class="card" style="width: 18rem;background:#8ababf;">
    <div class="card-body text-center">
      <h5 class="card-title ">Order Deliverd</h5>
      <hr>
      <h2 class="card-text">4</h2>
      
    </div>
  </div>
</div>
<div class="col-4">
  <div class="card" style="width: 18rem;background:#8ababf;">
    <div class="card-body text-center">
      <h5 class="card-title">Pending</h5>
      <hr>
      <h2 class="card-text">4</h2>
     
    </div>
  </div>
</div>
</div>
<br><br><br>

<table class="table table-success table-striped">
    <tr>
        <th>Product</th>
        <th>Status</th>
        <th>Update</th>
        <th>Delete</th>
    </tr>
    <tr>
        <td>shoe</td>
        <td>pending</td>
        <td><button class="btn btn-info">Update</button></td>
        <td><button class="btn btn-danger">Delete</button></td>
    
    </tr>
  
  </table>
  <br><br><br><br><br><br><br>

{% endblock content %}

customer/templates/customer_templates/customer_main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'css/customer_main.css' %}">
  {% block link %} {% endblock %}



  <title>Document</title>

</head>

<body>
  
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'common_app:index' %}">Eco</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'common_app:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'customer_app:cus_profile' %}">Profile</a>
          </li>
        </ul>
        <div class="form-inline my-2 my-lg-0">
          <button class="btn btn-warning" onclick="disp()">Login</button>

          <a href="{% url 'common_app:cart' %}">
            <img id="cart-icon" src="{% static 'images/cart.png' %}">
          </a>
          <p id="cart-total">0</p>

        </div>

      </div>
    </div>
  </nav>
  <div class="row" id="login_detail">
    <div class="col-9"></div>
    <div class="col">


      <div class="alert alert-success" role="alert">
        <div class="row text-center">
          <div class="col">
            <a href="{% url 'common_app:customer_login' %}" class="alert-link">customer login</a>
          </div>
          <div class="col">
            <a href="{% url 'common_app:seller_login' %}" class="alert-link">seller login</a>
          </div>
        </div>
      </div>
    </div>
  </div>



  <div class="container">
    <br>
    {% block content %}
   


    {% endblock content %}
  </div>
  <br><br><br>
  <div class="footer">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <div class="container-fluid ">
      <div id="social" class="col-md-6 col-md-offset-3 text-center">

        <a href="#" class="fa fa-facebook"></a>
        <a href="#" class="fa fa-twitter"></a>
        <a href="#" class="fa fa-instagram"></a>


      </div>

    </div>
  </div>
  </div>






  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"></script>

  <script>

    function disp() {

      var a = document.getElementById('login_detail')
      
      if (a.style.display == 'none') {
        a.style.display = 'flex';
      }
      else {
        a.style.display = 'none';

      }
    }
  </script>
</body>

</html>

seller/templates/seller_templates/seller_home.html
{% extends './seller_main.html' %}
{% load static %}
{% block content %}

<h1>seller home</h1>

{% endblock content %}

seller/templates/seller_templates/seller_main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="{% static 'css/customer_main.css' %}">
  {% block link %} {% endblock %}



  <title>Document</title>

</head>

<body>
  
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'common_app:index' %}">Eco</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'common_app:index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'customer_app:cus_profile' %}">Profile</a>
          </li>
        </ul>
        <div class="form-inline my-2 my-lg-0">
          <button class="btn btn-warning" onclick="disp()">Login</button>

          <a href="{% url 'common_app:cart' %}">
            <img id="cart-icon" src="{% static 'images/cart.png' %}">
          </a>
          <p id="cart-total">0</p>

        </div>

      </div>
    </div>
  </nav>
  <div class="row" id="login_detail">
    <div class="col-9"></div>
    <div class="col">


      <div class="alert alert-success" role="alert">
        <div class="row text-center">
          <div class="col">
            <a href="{% url 'common_app:customer_login' %}" class="alert-link">customer login</a>
          </div>
          <div class="col">
            <a href="{% url 'common_app:seller_login' %}" class="alert-link">seller login</a>
          </div>
        </div>
      </div>
    </div>
  </div>



  <div class="container">
    <br>
    {% block content %}
   


    {% endblock content %}
  </div>
  <br><br><br>
  <div class="footer">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <div class="container-fluid ">
      <div id="social" class="col-md-6 col-md-offset-3 text-center">

        <a href="#" class="fa fa-facebook"></a>
        <a href="#" class="fa fa-twitter"></a>
        <a href="#" class="fa fa-instagram"></a>


      </div>

    </div>
  </div>
  </div>






  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
    integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
    integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
    crossorigin="anonymous"></script>

  <script>

    function disp() {

      var a = document.getElementById('login_detail')
      
      if (a.style.display == 'none') {
        a.style.display = 'flex';
      }
      else {
        a.style.display = 'none';

      }
    }
  </script>
</body>

</html>